apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: tunkcalb/todo-backend-java:deploy
        imagePullPolicy: Always
